Fix flaky subtest f2fsslower in test_tools_smoke.py (#3531)
The f2fsslower.py may return earlier if the kernel does not
have required functions. For example, on my system,

  $ sudo python3.6 ./f2fsslower.py
  ERROR: no f2fs_file_operations in /proc/kallsyms. Exiting.
  HINT: the kernel should be built with CONFIG_KALLSYMS_ALL.
  $ echo $?
  0

So set allow_early to be True when testing f2fsslower.py
in test_tools_smoke.py.

Signed-off-by: Yonghong Song <yonghong.song@linux.dev>