bcc: Fix tracepoint struct generation
Commit 3087c61ed2c4 ([0]) changes `TASK_COMM_LEN` from macro to enum.
With this change, we have:
    field:char comm[TASK_COMM_LEN]; offset:8;       size:16;        signed:1;
in tracepoint format.

If users do NOT include proper headers, will result in:
    /virtual/main.c:4:12: error: use of undeclared identifier 'TASK_COMM_LEN'
            char comm[TASK_COMM_LEN];
                      ^
    1 error generated.

Let's handle this with BTF info.

Closes #4092.

  [0]: https://github.com/torvalds/linux/commit/3087c61ed2c48548b74dd343a5209b87082c682d

Signed-off-by: Hengqi Chen <chenhengqi@outlook.com>